// src/App.tsx
import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { WebviewWindow } from "@tauri-apps/api/webviewWindow";
import { confirm, message, open, save } from "@tauri-apps/plugin-dialog";
import {
  BookOpen,
  FileSpreadsheet,
  FolderOpen,
  GripVertical,
  Info,
  Plus,
  Rocket,
  Save,
  ScanSearch,
  Trash2,
} from "lucide-react";
import type {
  CurrentFileEvent,
  FilterMode,
  LogEvent,
  PageKey,
  ProgressEvent,
  Rule,
  Scheme,
  SheetChoice,
  SheetConflict,
  SheetMode,
  SummaryRequest,
  SummaryResult,
} from "./types";
import { getBrandSubtitle } from "./brandContent";
import { getRuleRowKey } from "./ruleKeys";
import { reorderRules } from "./ruleOrdering";
import { getSummaryCompletionPrompt } from "./summaryPrompt";
import { SupportWindowContent } from "./SupportWindowContent";
import { AboutPage } from "./AboutPage";
import { OcrPage } from "./OcrPage";
import { RuleImageImporter } from "./RuleImageImporter";
import { pages } from "./navigation";
import {
  getSupportViewFromSearch,
  getSupportWindowConfig,
  type SupportView,
} from "./supportWindows";

const emptyRule: Rule = {
  output_column: "",
  sheet_mode: "exact",
  sheet_value: "",
  cell: "",
};

const sampleRules: Rule[] = [
  {
    output_column: "货币资金",
    sheet_mode: "exact",
    sheet_value: "资产负债表",
    cell: "B7",
  },
  {
    output_column: "营业收入",
    sheet_mode: "contains",
    sheet_value: "利润",
    cell: "C12",
  },
  {
    output_column: "第一个 Sheet 样例",
    sheet_mode: "index",
    sheet_value: "1",
    cell: "A1",
  },
];

function getSheetConflictKey(conflict: SheetConflict): string {
  return `${conflict.file_path}::${conflict.rule_index}`;
}

function buildSheetChoices(
  conflicts: SheetConflict[],
  selectedSheets: Record<string, string>,
): SheetChoice[] {
  return conflicts.map((conflict) => ({
    file_path: conflict.file_path,
    rule_index: conflict.rule_index,
    sheet_name: selectedSheets[getSheetConflictKey(conflict)] ?? conflict.matched_sheets[0],
  }));
}

const brandSubtitle = getBrandSubtitle();
const supportView = getSupportViewFromSearch(window.location.search);

function App() {
  if (supportView !== "main") {
    return <SupportWindowContent view={supportView} />;
  }

  const [activePage, setActivePage] = useState<PageKey>("source");
  const [schemes, setSchemes] = useState<Scheme[]>([]);
  const [selectedScheme, setSelectedScheme] = useState("");
  const [schemeName, setSchemeName] = useState("");
  const [targetFolder, setTargetFolder] = useState("");
  const [outputFile, setOutputFile] = useState("");
  const [keyword, setKeyword] = useState("");
  const [filterMode, setFilterMode] = useState<FilterMode>("include");
  const [rules, setRules] = useState<Rule[]>(sampleRules);
  const [selectedRuleIndex, setSelectedRuleIndex] = useState<number | null>(null);
  const [draggedRuleIndex, setDraggedRuleIndex] = useState<number | null>(null);
  const [dragOverRuleIndex, setDragOverRuleIndex] = useState<number | null>(null);
  const [logs, setLogs] = useState<string[]>([]);
  const [currentFile, setCurrentFile] = useState("-");
  const [processed, setProcessed] = useState(0);
  const [total, setTotal] = useState(0);
  const [running, setRunning] = useState(false);
  const [sheetConflicts, setSheetConflicts] = useState<SheetConflict[]>([]);
  const [selectedSheets, setSelectedSheets] = useState<Record<string, string>>({});
  const [pendingRequest, setPendingRequest] = useState<SummaryRequest | null>(null);
  const [showRuleImageImporter, setShowRuleImageImporter] = useState(false);

  const activeTitle = pages.find((page) => page.key === activePage)?.label ?? "";
  const percent = total > 0 ? Math.round((processed / total) * 100) : 0;
  const selectedSchemeData = useMemo(
    () => schemes.find((scheme) => scheme.name === selectedScheme),
    [schemes, selectedScheme],
  );

  useEffect(() => {
    void refreshSchemes();
    const unlisteners = [
      listen<LogEvent>("summary-log", (event) => {
        appendLog(event.payload.level, event.payload.message);
      }),
      listen<ProgressEvent>("summary-progress", (event) => {
        setProcessed(event.payload.processed);
        setTotal(event.payload.total);
      }),
      listen<CurrentFileEvent>("summary-current-file", (event) => {
        setCurrentFile(event.payload.path);
      }),
    ];
    return () => {
      unlisteners.forEach((promise) => {
        void promise.then((unlisten) => unlisten());
      });
    };
  }, []);

  async function refreshSchemes() {
    try {
      const loaded = await invoke<Scheme[]>("load_schemes");
      setSchemes(loaded);
    } catch (error) {
      appendLog("WARN", String(error));
    }
  }

  function appendLog(level: LogEvent["level"], text: string) {
    const time = new Date().toLocaleTimeString("zh-CN", { hour12: false });
    setLogs((items) => [...items, `[${time}] [${level}] ${text}`]);
  }

  function collectScheme(): Scheme {
    return {
      name: schemeName,
      target_folder: targetFolder,
      output_file: outputFile,
      keyword,
      filter_mode: filterMode,
      rules,
    };
  }

  async function saveCurrentScheme() {
    try {
      await invoke("save_scheme", { scheme: collectScheme() });
      appendLog("DONE", `方案已保存：${schemeName}`);
      await refreshSchemes();
      setSelectedScheme(schemeName);
    } catch (error) {
      await message(String(error), { title: "保存方案失败", kind: "error" });
    }
  }

  function loadSelectedScheme() {
    if (!selectedSchemeData) {
      return;
    }
    setSchemeName(selectedSchemeData.name);
    setTargetFolder(selectedSchemeData.target_folder);
    setOutputFile(selectedSchemeData.output_file);
    setKeyword(selectedSchemeData.keyword);
    setFilterMode(selectedSchemeData.filter_mode);
    setRules(selectedSchemeData.rules.length ? selectedSchemeData.rules : [emptyRule]);
    appendLog("INFO", `已载入方案：${selectedSchemeData.name}`);
  }

  async function deleteSelectedScheme() {
    if (!selectedScheme) {
      return;
    }
    const ok = await confirm(`确认删除方案“${selectedScheme}”？`, {
      title: "删除方案",
      kind: "warning",
    });
    if (!ok) {
      return;
    }
    await invoke("delete_scheme", { name: selectedScheme });
    appendLog("DONE", `方案已删除：${selectedScheme}`);
    setSelectedScheme("");
    await refreshSchemes();
  }

  async function browseTargetFolder() {
    const selected = await open({
      directory: true,
      multiple: false,
      title: "选择包含 Excel 文件的文件夹",
    });
    if (typeof selected === "string") {
      setTargetFolder(selected);
    }
  }

  async function browseOutputFile() {
    const selected = await save({
      title: "选择汇总结果输出路径",
      defaultPath: "汇总结果.xlsx",
      filters: [{ name: "Excel 工作簿", extensions: ["xlsx"] }],
    });
    if (typeof selected === "string") {
      setOutputFile(selected);
    }
  }

  function updateRule(index: number, patch: Partial<Rule>) {
    setRules((items) =>
      items.map((rule, ruleIndex) =>
        ruleIndex === index ? { ...rule, ...patch } : rule,
      ),
    );
  }

  function addRule() {
    setRules((items) => [...items, emptyRule]);
    setSelectedRuleIndex(rules.length);
  }

  function deleteSelectedRule() {
    if (selectedRuleIndex === null) {
      return;
    }
    setRules((items) => items.filter((_, index) => index !== selectedRuleIndex));
    setSelectedRuleIndex(null);
  }

  function appendImportedRules(importedRules: Rule[]) {
    setRules((items) => [...items, ...importedRules]);
    setSelectedRuleIndex(rules.length);
    setShowRuleImageImporter(false);
    appendLog("DONE", `已从标注截图追加 ${importedRules.length} 条规则。`);
  }

  function startRuleDrag(event: React.DragEvent<HTMLButtonElement>, index: number) {
    setDraggedRuleIndex(index);
    setDragOverRuleIndex(index);
    setSelectedRuleIndex(index);
    event.dataTransfer.effectAllowed = "move";
    event.dataTransfer.setData("text/plain", String(index));
  }

  function dropRule(event: React.DragEvent<HTMLTableRowElement>, toIndex: number) {
    event.preventDefault();
    const transferIndex = Number(event.dataTransfer.getData("text/plain"));
    const fromIndex = draggedRuleIndex ?? transferIndex;

    if (Number.isInteger(fromIndex)) {
      const result = reorderRules(rules, fromIndex, toIndex, selectedRuleIndex);
      setRules(result.rules);
      setSelectedRuleIndex(result.selectedIndex);
    }

    setDraggedRuleIndex(null);
    setDragOverRuleIndex(null);
  }

  function endRuleDrag() {
    setDraggedRuleIndex(null);
    setDragOverRuleIndex(null);
  }

  async function runSummary() {
    if (running) {
      return;
    }
    const request: SummaryRequest = {
      target_folder: targetFolder,
      output_file: outputFile,
      keyword,
      filter_mode: filterMode,
      rules,
      sheet_choices: [],
    };

    if (!targetFolder || !outputFile) {
      await message("请先选择目标文件夹和输出文件。", {
        title: "配置不完整",
        kind: "warning",
      });
      return;
    }
    if (!rules.length) {
      await message("请至少配置一条规则。", {
        title: "规则为空",
        kind: "warning",
      });
      return;
    }
    const exists = await invoke<boolean>("path_exists", { path: outputFile });
    if (exists) {
      const overwrite = await confirm("输出文件已存在，是否覆盖？", {
        title: "确认覆盖",
        kind: "warning",
      });
      if (!overwrite) {
        return;
      }
    }

    try {
      const conflicts = await invoke<SheetConflict[]>("collect_sheet_conflicts", { request });
      if (conflicts.length > 0) {
        const initialSheets = Object.fromEntries(
          conflicts.map((conflict) => [
            getSheetConflictKey(conflict),
            conflict.matched_sheets[0],
          ]),
        );
        setSelectedSheets(initialSheets);
        setSheetConflicts(conflicts);
        setPendingRequest(request);
        appendLog(
          "WARN",
          `发现 ${conflicts.length} 处 Sheet 关键词命中多个 Sheet，请选择后继续。`,
        );
        return;
      }
    } catch (error) {
      await message(String(error), { title: "Sheet 冲突检查失败", kind: "error" });
      return;
    }

    await executeSummary(request);
  }

  async function executeSummary(request: SummaryRequest) {
    setRunning(true);
    setProcessed(0);
    setTotal(0);
    setCurrentFile("-");
    appendLog("INFO", "开始执行汇总。");
    try {
      const result = await invoke<SummaryResult>("run_summary", { request });
      appendLog(
        "DONE",
        `处理完成：${result.processed_files}/${result.total_files}，输出 ${result.output_path}`,
      );
      const shouldOpen = await confirm(getSummaryCompletionPrompt(), {
        title: "执行完成",
        kind: "info",
      });
      if (shouldOpen) {
        await invoke("open_output_file", { path: result.output_path });
      }
    } catch (error) {
      appendLog("ERROR", String(error));
      await message(String(error), { title: "汇总失败", kind: "error" });
    } finally {
      setRunning(false);
    }
  }

  function cancelSheetChoice() {
    setSheetConflicts([]);
    setSelectedSheets({});
    setPendingRequest(null);
    appendLog("INFO", "已取消 Sheet 选择。");
  }

  async function continueWithSheetChoices() {
    if (!pendingRequest) {
      return;
    }
    const request: SummaryRequest = {
      ...pendingRequest,
      sheet_choices: buildSheetChoices(sheetConflicts, selectedSheets),
    };
    setSheetConflicts([]);
    setSelectedSheets({});
    setPendingRequest(null);
    await executeSummary(request);
  }

  async function openHelpWindow() {
    const config = getSupportWindowConfig("help");
    const existing = await WebviewWindow.getByLabel(config.label);
    if (existing) {
      await existing.show();
      await existing.unminimize();
      await existing.setFocus();
      return;
    }
    const { label, ...windowOptions } = config;
    const supportWindow = new WebviewWindow(label, windowOptions);
    await supportWindow.once("tauri://error", (event) => {
      appendLog("ERROR", `打开${config.title}窗口失败：${String(event.payload)}`);
    });
  }

  return (
    <div className="app-shell">
      <aside className="side-nav">
        <div className="brand">
          <div className="brand-mark">
            <FileSpreadsheet size={26} />
          </div>
          <div>
            <h1>Financial Tool</h1>
            {brandSubtitle && <p>{brandSubtitle}</p>}
          </div>
        </div>
        <nav className="nav-list">
          {pages.map((page) => {
            const Icon = page.icon;
            return (
              <button
                key={page.key}
                className={activePage === page.key ? "nav-item active" : "nav-item"}
                onClick={() => setActivePage(page.key)}
              >
                <Icon size={22} />
                <span>{page.label}</span>
              </button>
            );
          })}
        </nav>
        <div className="side-note">
          <p>非递归扫描目标目录</p>
          <p>支持 .xlsx / .xlsm / .xltx / .xltm</p>
          <p>公式读取已保存缓存值</p>
        </div>
      </aside>

      <main className="workspace">
        <header className="window-bar" data-tauri-drag-region>
          <div>
            <h2>Financial Tool 财务工具箱</h2>
            <p>Excel 定向汇总、截图识字与规则定位</p>
          </div>
          <div className="window-actions">
            <button className="soft-button" onClick={() => void openHelpWindow()}>
              <Info size={19} />
              帮助说明
            </button>
          </div>
        </header>

        <section className="content-panel" key={activePage}>
          <div className="panel-heading">
            <div>
              <p className="eyebrow">当前页面</p>
              <h3>{activeTitle}</h3>
            </div>
            {activePage === "rules" && (
              <div className="toolbar">
                <button className="soft-button" onClick={() => setShowRuleImageImporter(true)}>
                  <ScanSearch size={18} />
                  图片生成规则
                </button>
                <button className="soft-button" onClick={addRule}>
                  <Plus size={18} />
                  新增规则
                </button>
                <button className="danger-button" onClick={deleteSelectedRule}>
                  <Trash2 size={18} />
                  删除选中
                </button>
                <button className="soft-button" onClick={() => setRules(sampleRules)}>
                  <BookOpen size={18} />
                  填充示例规则
                </button>
              </div>
            )}
          </div>

          {activePage === "scheme" && (
            <div className="form-grid">
              <label>
                <span>方案名称</span>
                <input
                  value={schemeName}
                  onChange={(event) => setSchemeName(event.target.value)}
                  placeholder="方案名称"
                />
              </label>
              <label>
                <span>已保存方案</span>
                <select
                  value={selectedScheme}
                  onChange={(event) => setSelectedScheme(event.target.value)}
                >
                  <option value="">选择已保存方案</option>
                  {schemes.map((scheme) => (
                    <option key={scheme.name} value={scheme.name}>
                      {scheme.name}
                    </option>
                  ))}
                </select>
              </label>
              <div className="button-row">
                <button className="soft-button" onClick={saveCurrentScheme}>
                  <Save size={18} />
                  保存方案
                </button>
                <button className="soft-button" onClick={loadSelectedScheme}>
                  <FolderOpen size={18} />
                  载入方案
                </button>
                <button className="danger-button" onClick={deleteSelectedScheme}>
                  <Trash2 size={18} />
                  删除方案
                </button>
              </div>
            </div>
          )}

          {activePage === "source" && (
            <div className="form-grid">
              <label className="wide-field">
                <span>目标文件夹</span>
                <div className="input-action">
                  <input
                    value={targetFolder}
                    onChange={(event) => setTargetFolder(event.target.value)}
                    placeholder="选择包含 Excel 文件的文件夹"
                  />
                  <button className="soft-button" onClick={browseTargetFolder}>
                    浏览
                  </button>
                </div>
              </label>
              <label className="wide-field">
                <span>输出文件</span>
                <div className="input-action">
                  <input
                    value={outputFile}
                    onChange={(event) => setOutputFile(event.target.value)}
                    placeholder="选择汇总结果输出路径，建议 .xlsx"
                  />
                  <button className="soft-button" onClick={browseOutputFile}>
                    浏览
                  </button>
                </div>
              </label>
              <label>
                <span>关键词</span>
                <input
                  value={keyword}
                  onChange={(event) => setKeyword(event.target.value)}
                  placeholder="为空时处理全部符合条件的 Excel 文件"
                />
              </label>
              <label>
                <span>筛选模式</span>
                <select
                  value={filterMode}
                  onChange={(event) => setFilterMode(event.target.value as FilterMode)}
                >
                  <option value="include">包含关键词</option>
                  <option value="exclude">排除关键词</option>
                </select>
              </label>
            </div>
          )}

          {activePage === "rules" && (
            <div className="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th
                      className="drag-column"
                      aria-label="拖动排序"
                      title="拖动左侧手柄调整规则顺序"
                    >
                      <GripVertical size={18} />
                    </th>
                    <th>输出列名</th>
                    <th>Sheet 模式</th>
                    <th>Sheet 值</th>
                    <th>单元格</th>
                  </tr>
                </thead>
                <tbody>
                  {rules.map((rule, index) => (
                    <tr
                      key={getRuleRowKey(index)}
                      className={[
                        selectedRuleIndex === index ? "selected-row" : "",
                        dragOverRuleIndex === index && draggedRuleIndex !== index
                          ? "drag-over-row"
                          : "",
                      ]
                        .filter(Boolean)
                        .join(" ")}
                      onClick={() => setSelectedRuleIndex(index)}
                      onDragOver={(event) => {
                        event.preventDefault();
                        event.dataTransfer.dropEffect = "move";
                        setDragOverRuleIndex(index);
                      }}
                      onDrop={(event) => dropRule(event, index)}
                    >
                      <td className="drag-cell">
                        <button
                          type="button"
                          className="drag-handle"
                          draggable
                          aria-label={`拖动第 ${index + 1} 条规则调整顺序`}
                          title="拖动调整顺序"
                          onClick={(event) => {
                            event.stopPropagation();
                            setSelectedRuleIndex(index);
                          }}
                          onDragStart={(event) => startRuleDrag(event, index)}
                          onDragEnd={endRuleDrag}
                        >
                          <GripVertical size={20} />
                        </button>
                      </td>
                      <td>
                        <input
                          value={rule.output_column}
                          onChange={(event) =>
                            updateRule(index, { output_column: event.target.value })
                          }
                        />
                      </td>
                      <td>
                        <select
                          value={rule.sheet_mode}
                          onChange={(event) =>
                            updateRule(index, { sheet_mode: event.target.value as SheetMode })
                          }
                        >
                          <option value="exact">exact - 精确匹配</option>
                          <option value="contains">contains - 包含关键词</option>
                          <option value="index">index - 按序号</option>
                        </select>
                      </td>
                      <td>
                        <input
                          value={rule.sheet_value}
                          onChange={(event) =>
                            updateRule(index, { sheet_value: event.target.value })
                          }
                        />
                      </td>
                      <td>
                        <input
                          value={rule.cell}
                          onChange={(event) => updateRule(index, { cell: event.target.value })}
                        />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {activePage === "run" && (
            <div className="run-layout">
              <div className="run-actions">
                <button className="primary-button" disabled={running} onClick={runSummary}>
                  <Rocket size={20} />
                  {running ? "正在汇总" : "开始汇总"}
                </button>
                <button className="soft-button" onClick={() => setLogs([])}>
                  清空日志
                </button>
                <div className="run-meta">当前处理文件：{currentFile}</div>
                <div className="run-count">
                  已处理 {processed} / {total}
                </div>
              </div>
              <div className="progress-bar">
                <div style={{ width: `${percent}%` }} />
                <span>{percent}%</span>
              </div>
              <pre className="log-console">{logs.join("\n")}</pre>
            </div>
          )}

          {activePage === "ocr" && <OcrPage onLog={appendLog} />}

          {activePage === "about" && <AboutPage />}
        </section>
      </main>

      {sheetConflicts.length > 0 && pendingRequest && (
        <div className="modal-backdrop" role="presentation">
          <div className="sheet-modal" role="dialog" aria-modal="true">
            <div className="sheet-modal-heading">
              <div>
                <p className="eyebrow">Sheet 匹配冲突</p>
                <h3>请选择实际要读取的 Sheet</h3>
              </div>
              <span>{sheetConflicts.length} 项</span>
            </div>
            <div className="sheet-conflict-list">
              {sheetConflicts.map((conflict) => {
                const key = getSheetConflictKey(conflict);
                return (
                  <label className="sheet-conflict-item" key={key}>
                    <span>
                      {conflict.file_name} / {conflict.output_column} / 关键词：
                      {conflict.sheet_value}
                    </span>
                    <select
                      value={selectedSheets[key] ?? conflict.matched_sheets[0]}
                      onChange={(event) =>
                        setSelectedSheets((items) => ({
                          ...items,
                          [key]: event.target.value,
                        }))
                      }
                    >
                      {conflict.matched_sheets.map((sheetName) => (
                        <option key={sheetName} value={sheetName}>
                          {sheetName}
                        </option>
                      ))}
                    </select>
                  </label>
                );
              })}
            </div>
            <div className="modal-actions">
              <button className="soft-button" onClick={cancelSheetChoice}>
                取消
              </button>
              <button className="primary-button" onClick={() => void continueWithSheetChoices()}>
                使用选择继续汇总
              </button>
            </div>
          </div>
        </div>
      )}

      {showRuleImageImporter && (
        <RuleImageImporter
          onClose={() => setShowRuleImageImporter(false)}
          onAppend={appendImportedRules}
        />
      )}

    </div>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { storeToRefs } from "pinia";
import { ElButton, ElConfigProvider } from "element-plus";
import zhCn from "element-plus/es/locale/lang/zh-cn";
import "element-plus/es/components/button/style/css";
import { invoke } from "@tauri-apps/api/core";
import { emitTo, listen, type UnlistenFn } from "@tauri-apps/api/event";
import { WebviewWindow } from "@tauri-apps/api/webviewWindow";
import { confirm, message, open, save } from "@tauri-apps/plugin-dialog";
import { BookOpen, ChevronLeft, ChevronRight, FileSpreadsheet, FolderOpen, GripVertical, Info, Plus, Rocket, Save, ScanSearch, Search, Trash2 } from "@lucide/vue";
import type { CurrentFileEvent, FilterMode, LogEvent, OcrRuntimeStatus, OcrTabKey, ProgressEvent, Rule, Scheme, SheetChoice, SheetConflict, SheetMode, SummaryRequest, SummaryResult, SummaryTabKey, WorkspaceKey } from "./types";
import { getBrandSubtitle } from "./brandContent";
import { getFileDisplayName } from "./fileDisplay";
import { getRuleRowKey } from "./ruleKeys";
import { reorderRules } from "./ruleOrdering";
import { getSchemePage } from "./schemePaging";
import { getSummaryCompletionPrompt } from "./summaryPrompt";
import { browserPreviewMessage, isTauriRuntime } from "./browserPreview";
import SupportWindowContent from "./SupportWindowContent.vue";
import AboutPage from "./AboutPage.vue";
import OcrPage from "./OcrPage.vue";
import OcrSettingsPage from "./OcrSettingsPage.vue";
import RuleImageImporter from "./RuleImageImporter.vue";
import TextCleanerPage from "./TextCleanerPage.vue";
import { ocrTabs, summaryTabs, workspacePages } from "./navigation";
import { isWorkspaceKey, getSupportViewFromSearch, getSupportWindowConfig, type SupportView } from "./supportWindows";
import { useAppNavigationStore } from "./stores/appNavigation";

const emptyRule: Rule = { output_column: "", sheet_mode: "exact", sheet_value: "", cell: "" };
const sampleRules: Rule[] = [
  { output_column: "货币资金", sheet_mode: "exact", sheet_value: "资产负债表", cell: "B7" },
  { output_column: "营业收入", sheet_mode: "contains", sheet_value: "利润", cell: "C12" },
  { output_column: "第一个 Sheet 样例", sheet_mode: "index", sheet_value: "1", cell: "A1" },
];
const brandSubtitle = getBrandSubtitle();
const supportView = getSupportViewFromSearch(window.location.search);
const browserPreview = !isTauriRuntime();
let ocrStartupPromise: Promise<OcrRuntimeStatus> | null = null;
let unlisteners: UnlistenFn[] = [];

const navigationStore = useAppNavigationStore();
const { activeWorkspace, activeSummaryTab, activeOcrTab } = storeToRefs(navigationStore);
const schemes = ref<Scheme[]>([]);
const selectedScheme = ref("");
const schemeName = ref("");
const targetFolder = ref("");
const outputFile = ref("");
const keyword = ref("");
const filterMode = ref<FilterMode>("include");
const rules = ref<Rule[]>(sampleRules.map((rule) => ({ ...rule })));
const selectedRuleIndex = ref<number | null>(null);
const draggedRuleIndex = ref<number | null>(null);
const dragOverRuleIndex = ref<number | null>(null);
const logs = ref<string[]>([]);
const currentFile = ref("-");
const processed = ref(0);
const total = ref(0);
const running = ref(false);
const sheetConflicts = ref<SheetConflict[]>([]);
const selectedSheets = ref<Record<string, string>>({});
const pendingRequest = ref<SummaryRequest | null>(null);
const showRuleImageImporter = ref(false);
const schemeQuery = ref("");
const schemePage = ref(1);

const activeTitle = computed(() => activeWorkspace.value === "summary"
  ? summaryTabs.find((tab) => tab.key === activeSummaryTab.value)?.label ?? ""
  : activeWorkspace.value === "ocr"
    ? ocrTabs.find((tab) => tab.key === activeOcrTab.value)?.label ?? ""
    : workspacePages.find((page) => page.key === activeWorkspace.value)?.label ?? "");
const activeKicker = computed(() => activeWorkspace.value === "summary" ? "汇总功能" : activeWorkspace.value === "ocr" ? "OCR 工具" : activeWorkspace.value === "text-cleaner" ? "剪贴板工具" : "应用信息");
const contentKey = computed(() => `${activeWorkspace.value}-${activeWorkspace.value === "summary" ? activeSummaryTab.value : activeWorkspace.value === "ocr" ? activeOcrTab.value : activeWorkspace.value}`);
const percent = computed(() => total.value > 0 ? Math.round((processed.value / total.value) * 100) : 0);
const selectedSchemeData = computed(() => schemes.value.find((scheme) => scheme.name === selectedScheme.value));
const schemePageData = computed(() => getSchemePage(schemes.value, schemeQuery.value, schemePage.value));

watch(() => schemePageData.value.currentPage, (page) => { schemePage.value = page; });

function getSheetConflictKey(conflict: SheetConflict) { return `${conflict.file_path}::${conflict.rule_index}`; }
function buildSheetChoices(conflicts: SheetConflict[], selections: Record<string, string>): SheetChoice[] {
  return conflicts.map((conflict) => ({ file_path: conflict.file_path, rule_index: conflict.rule_index, sheet_name: selections[getSheetConflictKey(conflict)] ?? conflict.matched_sheets[0] }));
}
function initializeOcrAtStartup() {
  if (browserPreview) return Promise.resolve<OcrRuntimeStatus>({ version: "浏览器预览", bundled: false, prepared: false, message: "浏览器预览不加载本地 Umi-OCR 组件。" });
  ocrStartupPromise ??= invoke<OcrRuntimeStatus>("prepare_ocr_runtime");
  return ocrStartupPromise;
}
function appendLog(level: LogEvent["level"], text: string) {
  const time = new Date().toLocaleTimeString("zh-CN", { hour12: false });
  logs.value.push(`[${time}] [${level}] ${text}`);
}
async function refreshSchemes() {
  if (browserPreview) return;
  try { schemes.value = await invoke<Scheme[]>("load_schemes"); }
  catch (error) { appendLog("WARN", String(error)); }
}
function collectScheme(): Scheme {
  return { name: schemeName.value, target_folder: targetFolder.value, output_file: outputFile.value, keyword: keyword.value, filter_mode: filterMode.value, rules: rules.value };
}
async function saveCurrentScheme() {
  const scheme = collectScheme();
  if (browserPreview) {
    if (!scheme.name.trim()) { window.alert("请先输入方案名称后再保存预览方案。"); return; }
    schemes.value = [...schemes.value.filter((item) => item.name !== scheme.name), scheme];
    selectedScheme.value = scheme.name; schemeQuery.value = ""; schemePage.value = 1;
    appendLog("INFO", `浏览器预览已暂存方案：${scheme.name}`); return;
  }
  try {
    await invoke("save_scheme", { scheme }); appendLog("DONE", `方案已保存：${schemeName.value}`);
    await refreshSchemes(); selectedScheme.value = schemeName.value; schemeQuery.value = ""; schemePage.value = 1;
  } catch (error) { await message(String(error), { title: "保存方案失败", kind: "error" }); }
}
function applyScheme(scheme: Scheme) {
  selectedScheme.value = scheme.name; schemeName.value = scheme.name; targetFolder.value = scheme.target_folder;
  outputFile.value = scheme.output_file; keyword.value = scheme.keyword; filterMode.value = scheme.filter_mode;
  rules.value = (scheme.rules.length ? scheme.rules : [emptyRule]).map((rule) => ({ ...rule }));
  appendLog("INFO", `已载入方案：${scheme.name}`);
}
function loadSelectedScheme() { if (selectedSchemeData.value) applyScheme(selectedSchemeData.value); }
async function deleteSelectedScheme() {
  if (!selectedScheme.value) return;
  const name = selectedScheme.value;
  if (browserPreview) { schemes.value = schemes.value.filter((scheme) => scheme.name !== name); selectedScheme.value = ""; appendLog("INFO", `浏览器预览已移除方案：${name}`); return; }
  if (!await confirm(`确认删除方案“${name}”？`, { title: "删除方案", kind: "warning" })) return;
  await invoke("delete_scheme", { name }); appendLog("DONE", `方案已删除：${name}`); selectedScheme.value = ""; await refreshSchemes();
}
async function browseTargetFolder() {
  if (browserPreview) { window.alert(browserPreviewMessage); return; }
  const selected = await open({ directory: true, multiple: false, title: "选择包含 Excel 文件的文件夹" });
  if (typeof selected === "string") targetFolder.value = selected;
}
async function browseOutputFile() {
  if (browserPreview) { window.alert(browserPreviewMessage); return; }
  const selected = await save({ title: "选择汇总结果输出路径", defaultPath: "汇总结果.xlsx", filters: [{ name: "Excel 工作簿", extensions: ["xlsx"] }] });
  if (typeof selected === "string") outputFile.value = selected;
}
function updateRule(index: number, patch: Partial<Rule>) { rules.value[index] = { ...rules.value[index], ...patch }; }
function addRule() { rules.value.push({ ...emptyRule }); selectedRuleIndex.value = rules.value.length - 1; }
function deleteSelectedRule() { if (selectedRuleIndex.value === null) return; rules.value.splice(selectedRuleIndex.value, 1); selectedRuleIndex.value = null; }
function appendImportedRules(importedRules: Rule[]) { const start = rules.value.length; rules.value.push(...importedRules); selectedRuleIndex.value = start; appendLog("DONE", `已从 Excel 截图追加 ${importedRules.length} 条规则。`); }
function startRuleDrag(event: DragEvent, index: number) { draggedRuleIndex.value = index; dragOverRuleIndex.value = index; selectedRuleIndex.value = index; if (event.dataTransfer) { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", String(index)); } }
function dropRule(event: DragEvent, toIndex: number) {
  event.preventDefault(); const transferIndex = Number(event.dataTransfer?.getData("text/plain")); const fromIndex = draggedRuleIndex.value ?? transferIndex;
  if (Number.isInteger(fromIndex)) { const result = reorderRules(rules.value, fromIndex, toIndex, selectedRuleIndex.value); rules.value = result.rules; selectedRuleIndex.value = result.selectedIndex; }
  draggedRuleIndex.value = null; dragOverRuleIndex.value = null;
}
function endRuleDrag() { draggedRuleIndex.value = null; dragOverRuleIndex.value = null; }
async function runSummary() {
  if (browserPreview) { window.alert(browserPreviewMessage); return; }
  if (running.value) return;
  const request: SummaryRequest = { target_folder: targetFolder.value, output_file: outputFile.value, keyword: keyword.value, filter_mode: filterMode.value, rules: rules.value, sheet_choices: [] };
  if (!targetFolder.value || !outputFile.value) { await message("请先选择目标文件夹和输出文件。", { title: "配置不完整", kind: "warning" }); return; }
  if (!rules.value.length) { await message("请至少配置一条规则。", { title: "规则为空", kind: "warning" }); return; }
  if (await invoke<boolean>("path_exists", { path: outputFile.value }) && !await confirm("输出文件已存在，是否覆盖？", { title: "确认覆盖", kind: "warning" })) return;
  try {
    const conflicts = await invoke<SheetConflict[]>("collect_sheet_conflicts", { request });
    if (conflicts.length) {
      selectedSheets.value = Object.fromEntries(conflicts.map((conflict) => [getSheetConflictKey(conflict), conflict.matched_sheets[0]]));
      sheetConflicts.value = conflicts; pendingRequest.value = request; appendLog("WARN", `发现 ${conflicts.length} 处 Sheet 关键词命中多个 Sheet，请选择后继续。`); return;
    }
  } catch (error) { await message(String(error), { title: "Sheet 冲突检查失败", kind: "error" }); return; }
  await executeSummary(request);
}
async function executeSummary(request: SummaryRequest) {
  running.value = true; processed.value = 0; total.value = 0; currentFile.value = "-"; appendLog("INFO", "开始执行汇总。");
  try {
    const result = await invoke<SummaryResult>("run_summary", { request });
    appendLog("DONE", `处理完成：${result.processed_files}/${result.total_files}，输出 ${getFileDisplayName(result.output_path)}`);
    if (await confirm(getSummaryCompletionPrompt(), { title: "执行完成", kind: "info" })) await invoke("open_output_file", { path: result.output_path });
  } catch (error) { appendLog("ERROR", String(error)); await message(String(error), { title: "汇总失败", kind: "error" }); }
  finally { running.value = false; }
}
function cancelSheetChoice() { sheetConflicts.value = []; selectedSheets.value = {}; pendingRequest.value = null; appendLog("INFO", "已取消 Sheet 选择。"); }
async function continueWithSheetChoices() {
  if (!pendingRequest.value) return;
  const request = { ...pendingRequest.value, sheet_choices: buildSheetChoices(sheetConflicts.value, selectedSheets.value) };
  sheetConflicts.value = []; selectedSheets.value = {}; pendingRequest.value = null; await executeSummary(request);
}
async function openSupportWindow(view: Exclude<SupportView, "main">, returnWorkspace: WorkspaceKey = activeWorkspace.value) {
  const config = getSupportWindowConfig(view, returnWorkspace);
  if (browserPreview) { window.open(config.url, "_blank", "noopener,noreferrer"); return; }
  const existing = await WebviewWindow.getByLabel(config.label);
  if (existing) { await emitTo(config.label, "support-return-workspace", returnWorkspace); await existing.show(); await existing.unminimize(); await existing.setFocus(); return; }
  const { label, ...windowOptions } = config; const supportWindow = new WebviewWindow(label, windowOptions);
  await supportWindow.once("tauri://error", (event) => appendLog("ERROR", `打开${config.title}窗口失败：${String(event.payload)}`));
}

onMounted(async () => {
  if (supportView !== "main") return;
  if (browserPreview) { appendLog("INFO", browserPreviewMessage); return; }
  await refreshSchemes(); void initializeOcrAtStartup().catch((error) => appendLog("WARN", `Umi-OCR 自动加载失败：${String(error)}`));
  unlisteners = await Promise.all([
    listen<WorkspaceKey>("navigate-workspace", ({ payload }) => { if (isWorkspaceKey(payload)) activeWorkspace.value = payload; }),
    listen<LogEvent>("summary-log", ({ payload }) => appendLog(payload.level, payload.message)),
    listen<ProgressEvent>("summary-progress", ({ payload }) => { processed.value = payload.processed; total.value = payload.total; }),
    listen<CurrentFileEvent>("summary-current-file", ({ payload }) => { currentFile.value = payload.path; }),
  ]);
});
onBeforeUnmount(() => unlisteners.forEach((unlisten) => unlisten()));
</script>

<template>
  <ElConfigProvider :locale="zhCn">
    <SupportWindowContent v-if="supportView !== 'main'" :view="supportView" />
    <div v-else class="app-shell">
    <aside class="side-nav">
      <div class="brand"><div class="brand-mark"><FileSpreadsheet :size="26" /></div><div><h1>Financial Tool</h1><p v-if="brandSubtitle">{{ brandSubtitle }}</p></div></div>
      <nav class="nav-list">
        <button v-for="page in workspacePages" :key="page.key" :class="activeWorkspace === page.key ? 'nav-item active' : 'nav-item'" @click="activeWorkspace = page.key">
          <component :is="page.icon" :size="22" /><span>{{ page.label }}</span>
        </button>
      </nav>
      <div class="side-note"><p>非递归扫描目标目录</p><p>支持 .xlsx / .xlsm / .xltx / .xltm</p><p>公式读取已保存缓存值</p></div>
    </aside>
    <main class="workspace">
      <header class="window-bar" data-tauri-drag-region><div><h2>Financial Tool 财务工具箱</h2><p>Excel 定向汇总、截图识字与剪贴板清洗</p></div><div class="window-actions"><ElButton class="soft-button" @click="openSupportWindow('help', activeWorkspace)"><Info :size="19" />帮助说明</ElButton></div></header>
      <section class="content-panel">
        <div class="panel-heading"><div><p class="eyebrow">{{ activeKicker }}</p><h3>{{ activeTitle }}</h3></div>
          <div v-if="activeWorkspace === 'summary' && activeSummaryTab === 'rules'" class="toolbar">
            <button class="soft-button" @click="showRuleImageImporter = true"><ScanSearch :size="18" />图片生成规则</button>
            <button class="soft-button" @click="addRule"><Plus :size="18" />新增规则</button>
            <button class="danger-button" @click="deleteSelectedRule"><Trash2 :size="18" />删除选中</button>
            <button class="soft-button" @click="rules = sampleRules.map((rule) => ({ ...rule }))"><BookOpen :size="18" />填充示例规则</button>
          </div>
        </div>
        <nav v-if="activeWorkspace === 'summary'" class="workspace-tabs" role="tablist" aria-label="汇总功能标签">
          <button v-for="tab in summaryTabs" :key="tab.key" type="button" role="tab" :aria-selected="activeSummaryTab === tab.key" :class="activeSummaryTab === tab.key ? 'workspace-tab active' : 'workspace-tab'" @click="activeSummaryTab = tab.key"><component :is="tab.icon" :size="18" /><span>{{ tab.label }}</span></button>
        </nav>
        <nav v-if="activeWorkspace === 'ocr'" class="workspace-tabs" role="tablist" aria-label="截图识字标签">
          <button v-for="tab in ocrTabs" :key="tab.key" type="button" role="tab" :aria-selected="activeOcrTab === tab.key" :class="activeOcrTab === tab.key ? 'workspace-tab active' : 'workspace-tab'" @click="activeOcrTab = tab.key"><component :is="tab.icon" :size="18" /><span>{{ tab.label }}</span></button>
        </nav>
        <div class="feature-content" :key="contentKey">
          <div v-if="activeWorkspace === 'summary' && activeSummaryTab === 'scheme'" class="scheme-page">
            <div class="scheme-editor"><label><span>方案名称</span><input v-model="schemeName" placeholder="方案名称" /></label><div class="button-row">
              <button class="soft-button" @click="saveCurrentScheme"><Save :size="18" />保存方案</button>
              <button class="soft-button" :disabled="!selectedSchemeData" @click="loadSelectedScheme"><FolderOpen :size="18" />载入方案</button>
              <button class="danger-button" :disabled="!selectedSchemeData" @click="deleteSelectedScheme"><Trash2 :size="18" />删除方案</button>
            </div></div>
            <section class="scheme-library" aria-labelledby="saved-schemes-title">
              <div class="scheme-library-heading"><div><h4 id="saved-schemes-title">已保存方案</h4><span>共 {{ schemePageData.totalItems }} 个方案</span></div><label class="scheme-search"><Search :size="18" /><input v-model="schemeQuery" placeholder="搜索方案名称" aria-label="搜索已保存方案" @input="schemePage = 1" /></label></div>
              <div class="scheme-list" role="listbox" aria-label="已保存方案">
                <button v-for="scheme in schemePageData.items" :key="scheme.name" type="button" role="option" :aria-selected="selectedScheme === scheme.name" :class="selectedScheme === scheme.name ? 'scheme-list-item selected' : 'scheme-list-item'" @click="selectedScheme = scheme.name" @dblclick="applyScheme(scheme)"><FileSpreadsheet :size="20" /><span class="scheme-list-name">{{ scheme.name }}</span><span class="scheme-list-meta">{{ scheme.rules.length }} 条规则</span><span class="scheme-list-filter">{{ scheme.keyword ? `关键词：${scheme.keyword}` : '全部 Excel 文件' }}</span></button>
                <div v-if="!schemePageData.items.length" class="scheme-empty">没有匹配的已保存方案</div>
              </div>
              <div class="scheme-pagination"><span>第 {{ schemePageData.currentPage }} / {{ schemePageData.totalPages }} 页</span><div><button type="button" class="icon-button" :disabled="schemePageData.currentPage <= 1" title="上一页" @click="schemePage = Math.max(1, schemePage - 1)"><ChevronLeft :size="19" /></button><button type="button" class="icon-button" :disabled="schemePageData.currentPage >= schemePageData.totalPages" title="下一页" @click="schemePage = Math.min(schemePageData.totalPages, schemePage + 1)"><ChevronRight :size="19" /></button></div></div>
            </section>
          </div>
          <div v-if="activeWorkspace === 'summary' && activeSummaryTab === 'source'" class="form-grid">
            <label class="wide-field"><span>目标文件夹</span><div class="input-action"><input v-model="targetFolder" placeholder="选择包含 Excel 文件的文件夹" /><button class="soft-button" @click="browseTargetFolder">浏览</button></div></label>
            <label class="wide-field"><span>输出文件</span><div class="input-action"><div class="output-file-field"><span v-if="outputFile" class="output-file-name" :title="outputFile">{{ getFileDisplayName(outputFile) }}</span><span v-else class="output-file-placeholder">尚未选择输出文件</span></div><button class="soft-button" @click="browseOutputFile">浏览</button></div></label>
            <label><span>关键词</span><input v-model="keyword" placeholder="为空时处理全部符合条件的 Excel 文件" /></label>
            <label><span>筛选模式</span><select v-model="filterMode"><option value="include">包含关键词</option><option value="exclude">排除关键词</option></select></label>
          </div>
          <div v-if="activeWorkspace === 'summary' && activeSummaryTab === 'rules'" class="table-wrap"><table><thead><tr><th class="drag-column" aria-label="拖动排序" title="拖动左侧手柄调整规则顺序"><GripVertical :size="18" /></th><th>输出列名</th><th>Sheet 模式</th><th>Sheet 值</th><th>单元格</th></tr></thead><tbody>
            <tr v-for="(rule, index) in rules" :key="getRuleRowKey(index)" :class="[selectedRuleIndex === index ? 'selected-row' : '', dragOverRuleIndex === index && draggedRuleIndex !== index ? 'drag-over-row' : '']" @click="selectedRuleIndex = index" @dragover.prevent="dragOverRuleIndex = index" @drop="dropRule($event, index)">
              <td class="drag-cell"><button type="button" class="drag-handle" draggable="true" :aria-label="`拖动第 ${index + 1} 条规则调整顺序`" title="拖动调整顺序" @click.stop="selectedRuleIndex = index" @dragstart="startRuleDrag($event, index)" @dragend="endRuleDrag"><GripVertical :size="20" /></button></td>
              <td><input :value="rule.output_column" @input="updateRule(index, { output_column: ($event.target as HTMLInputElement).value })" /></td>
              <td><select :value="rule.sheet_mode" @change="updateRule(index, { sheet_mode: ($event.target as HTMLSelectElement).value as SheetMode })"><option value="exact">exact - 精确匹配</option><option value="contains">contains - 包含关键词</option><option value="index">index - 按序号</option></select></td>
              <td><input :value="rule.sheet_value" @input="updateRule(index, { sheet_value: ($event.target as HTMLInputElement).value })" /></td>
              <td><input :value="rule.cell" @input="updateRule(index, { cell: ($event.target as HTMLInputElement).value })" /></td>
            </tr>
          </tbody></table></div>
          <div v-if="activeWorkspace === 'summary' && activeSummaryTab === 'run'" class="run-layout"><div class="run-actions"><button class="primary-button" :disabled="running" @click="runSummary"><Rocket :size="20" />{{ running ? '正在汇总' : '开始汇总' }}</button><button class="soft-button" @click="logs = []">清空日志</button><div class="run-meta">当前处理文件：{{ currentFile }}</div><div class="run-count">已处理 {{ processed }} / {{ total }}</div></div><div class="progress-bar"><div :style="{ width: `${percent}%` }" /><span>{{ percent }}%</span></div><pre class="log-console">{{ logs.join('\n') }}</pre></div>
          <OcrPage v-if="activeWorkspace === 'ocr' && activeOcrTab === 'capture'" :on-log="appendLog" />
          <OcrSettingsPage v-if="activeWorkspace === 'ocr' && activeOcrTab === 'settings'" :on-log="appendLog" />
          <TextCleanerPage v-if="activeWorkspace === 'text-cleaner'" :on-log="appendLog" :on-open-regex-tutorial="() => openSupportWindow('regex', 'text-cleaner')" />
          <AboutPage v-if="activeWorkspace === 'about'" />
        </div>
      </section>
    </main>
    <div v-if="sheetConflicts.length > 0 && pendingRequest" class="modal-backdrop" role="presentation"><div class="sheet-modal" role="dialog" aria-modal="true"><div class="sheet-modal-heading"><div><p class="eyebrow">Sheet 匹配冲突</p><h3>请选择实际要读取的 Sheet</h3></div><span>{{ sheetConflicts.length }} 项</span></div><div class="sheet-conflict-list">
      <label v-for="conflict in sheetConflicts" :key="getSheetConflictKey(conflict)" class="sheet-conflict-item"><span>{{ conflict.file_name }} / {{ conflict.output_column }} / 关键词：{{ conflict.sheet_value }}</span><select v-model="selectedSheets[getSheetConflictKey(conflict)]"><option v-for="sheetName in conflict.matched_sheets" :key="sheetName" :value="sheetName">{{ sheetName }}</option></select></label>
    </div><div class="modal-actions"><button class="soft-button" @click="cancelSheetChoice">取消</button><button class="primary-button" @click="continueWithSheetChoices">使用选择继续汇总</button></div></div></div>
    <RuleImageImporter v-if="showRuleImageImporter" :on-close="() => { showRuleImageImporter = false; }" :on-append="appendImportedRules" />
    </div>
  </ElConfigProvider>
</template>
